name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context # Object or collection of data with some general information about Github workflow and event trigger
        run: echo "${{ toJSON(github) }}"